### ISSUE TITLE
Thanks for your incredible work on dockerized cnpmjs.org!

### ISSUE THREAD

**Issue by Firef0x** [hbrls/docker-cnpm#1]
Hello @hbrls ,

Thanks for your incredible work on dockerized cnpmjs.org! :+1:  It helps me to build a private NPM registry in an hour on my boss's demand :joy: . I have forked your project and added `oss-cnpm` support based on your image.

It's a good manner to list you in the `Contributors`. Could I list it like `Albert 理斯特` in https://github.com/Firef0x/docker-cnpmjs-oss ?

Hope for your reply!

Yours sincerely!

**Comment by hbrls** [comment]
That's OK @Firef0x. Glad it helped you. You may list your repo after https://github.com/cnpm/cnpmjs.org/issues/903 too, so that other people can use it.
